-- baltic -> northern_europe
-- baltic_main -> baltic -> northern_europe
-- china_east_main -> china_main
-- china_main
-- china_north_main -> china_main
-- china_south_main -> china_main
-- finland_main -> baltic -> northern_europe
-- kattegat -> scandinavia -> northern_europe
-- northern_europe
-- north_europe_main -> northern_europe
-- north_europe_sub -> northern_europe
-- norway_north_west -> scandinavia -> northern_europe
-- norway_south_east -> scandinavia -> northern_europe
-- norway_south_west -> scandinavia -> northern_europe
-- poland_main -> baltic -> northern_europe
-- russia_north_west -> northern_europe
-- scandinavia -> northern_europe
-- stockholm_area -> scandinavia -> northern_europe
-- uk_main -> north_europe_main -> northern_europe
-- uk_sub -> north_europe_sub -> northern_europe


-- TODO: Create closure table?
